# Generated by Django 2.1.5 on 2019-01-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20190128_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Edad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
