# Generated by Django 2.1.5 on 2019-02-01 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0003_profile_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255)),
                ('Marca', models.CharField(max_length=255)),
                ('Modelo', models.DateField(max_length=10, null=True)),
            ],
        ),        
    ]
