# Generated by Django 2.1.5 on 2019-02-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='Imei',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='Marca',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='Modelo',
            field=models.DateField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='Nombre',
            field=models.CharField(max_length=50),
        ),
    ]
