# Generated by Django 2.1.5 on 2019-02-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_auto_20190201_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='Modelo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
