# Generated by Django 2.1.5 on 2019-02-01 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Unidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitud', models.CharField(max_length=255)),
                ('Longitud', models.CharField(max_length=255)),
                ('Fecha', models.DateField(max_length=10, null=True)),
                ('Hora', models.TimeField(max_length=50, null=True)),
                ('Imei', models.CharField(max_length=50)),
                ('Unidad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Unidades.Unidades')),
            ],
        ),
    ]
