# Generated by Django 2.1.5 on 2019-02-01 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps',
            name='Unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Unidades.Unidades'),
        ),
    ]
